# Generated by Django 4.1.7 on 2023-04-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('date', models.DateField(verbose_name='date')),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount_usd', models.IntegerField()),
            ],
        ),
    ]
